config/routes.rb
Rails.application.routes.draw do

  # get 'stargazing/new'
  root 'sessions#home'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
    
  
    resources :users
    #resources :stargazings, only: [:index]
    
    resources :stargazings
    
      resources :constellations do
        resources :stargazings
          #resources :stargazings, except: [:index]
      end
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constellation.rb
class Constellation < ApplicationRecord
    has_many :stargazings
    has_many :users, through: :stargazings
    validates :constellation_name, presence: true
  
   #ActiveRecord query 2
#    scope :alpha, -> { order(:constellation_name)}
    scope :sorted, -> { order(:constellation_name) }
end

app/models/stargazing.rb
class Stargazing < ApplicationRecord
    belongs_to :user
    belongs_to :constellation
    
    # def self.find_by_constellation_id(id)
    #     where(constellation_id: id)
    # end

    # def self.alpha_order
    #     order('constellation_name')
    # end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :stargazings
    has_many :constellations, through: :stargazings
    has_secure_password
    validates :username, presence: true, uniqueness: { case_sensitive: false }
    validates :username, length: {minimum: 4 }


    def self.from_omniauth(auth) #=> user that's found or user that's created
        find_or_create_by(username: auth[:info][:email]) do |user|
        user.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #  protect_from_forgery with: :exception
      protect_from_forgery
    # protect_from_forgery with: :null_session

    before_action :redirect_if_not_logged_in

    helper_method :current_user, :logged_in?

     def logged_in?
    !!session[:user_id]
    #  current_user
     end

    #  def logged_in?
    #     !!current_user 
    # end

     def redirect_if_not_logged_in
        redirect_to login_path unless logged_in?
     end

    def current_user
        # User.find_by(id: session[:user_id]) if session[:user_id]
         User.find_by(id: session[:user_id]) if session[:user_id] if session[:user_id]
        #   @current_user ||=user.find_by_id(session[:user_id]) if session[:user_id]
        # @current_user ||=user.find(session[:user_id])
        #if the current user is true it will set it equal to the user in the current session
    end


end

app/controllers/constellations_controller.rb
class ConstellationsController < ApplicationController
    before_action :set_cons, only: [:show, :edit, :update, :destroy]

    def index
        @constellations = Constellation.all.sorted
    end

    # def index
    #     @constellations = Constellation.where(:user_id => current_user.id)
    # end


 
    def show
    end

    def new
        @constellation = Constellation.new
    end
    
    def create
        @constellation = Constellation.new(cons_params)
        
        if @constellation.save
            redirect_to constellation_path(@constellation)
        else 
            render :new
        end
    end

        def edit
        end

        def update
            if @constellation.update(cons_params)
                redirect_to constellation_path(@constellation)
            else
                render :edit
            end
        end

        def destroy
            if @constellation.destroy
                redirect_to constellations_path
            else
                flash.now[:error] = "Please try again"
            end
        end

        private

        def cons_params
            params.require(:constellation).permit(:constellation_name, :star_name, :description, :image_url)
        end

        def set_cons
            @constellation = Constellation.find_by_id(params[:id])
        end
    end

app/controllers/session_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
    end

    def home
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :redirect_if_not_logged_in
    
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
             session[:user_id] = @user.id
             redirect_to constellations_path(@constellation)
        else
             flash.now[:error] = "Wrong login. Please try again."
             render :new
        end
   end

    def omniauth
        @user = user.from_omniauth(auth)
        if @user.valid?
             session[:user_id] = @user.id
             redirect_to root_path
        else
             redirect_to login_path
        end
   end

    def destroy
        session.clear
        redirect_to login_path
    end

    protected 

    def auth
        request.env('omniauth.auth')
    end
end

app/controllers/stargazings_controller.rb
class StargazingsController < ApplicationController
    # before_action :only []

    # def index
    #     @stargazings = Stargazing.all
    #     # @constellation = Constellation.all
    # end


    def index
        @stargazings = Stargazing.all
    end

    def show
        @stargazing = Stargazing.find(params[:id])
    end

    def new
        @stargazing = Stargazing.new
         @constellations = Constellation.all
    end

    def create 
        @stargazing = Stargazing.new(star_params)
        if @stargazing.save
            redirect_to stargazing_path(@stargazing)
        else
            render :new
        end
    end          # if @stargazing.save
        #     redirect_to stargazing_path
            #add flash message
    #     else
    #         render :new
    #     end
    # end

    def edit
        @stargazing = Stargazing.find(params[:id])
        @constellations = Constellation.all
    end

    def update 
        @stargazing = Stargazing.find(params[:id])
        @stargazing.update(star_params)
        redirect_to stargazing_path(@stargazing)
    end

    private

    def star_params
        params.require(:stargazing).permit(:location, :weather, :time, :constellation_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
    before_action :set_user, only: [:show, :edit, :update, :delete]

    #loads the signup form

    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    #signup 
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
        #  flash.now[:message] = "You're in!"
          redirect_to root_path(@user)
        else
            # flash.now[:message] = "Please try again"
            render :new
        end
    end

    def edit
        set_user
    end

    def update
        # @user = User.find_by_id(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        set_user 
        @user.delete
        redirect_to users_path
        flash.now[:error] = "You have successfully deleted your account!"
    end  
        
    private
    def user_params
        params.require(:user).permit(:username, :password, :profile_image, :bio)
    end

    def set_user
        @user = User.find_by_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

def render_navigation
    if session[:user_id]
        link_to 'logout', '/logout', method: 'delete'
    else
       link_to('login', '/login') + " " + link_to('signup', '/signup')
    end
end

app/helpers/constellations_helper.rb
module ConstellationsHelper
end

app/helpers/stargazings_helper.rb
module StargazingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/constellations/edit.html.erb
<%=render partial: 'cons', locals: {constellation: @constellation} %>


<%=link_to "Home", root_path%>
<%=link_to "Constellations", constellations_path(@constellation)%> |
<%=link_to "Add a Constellation", new_constellation_path(@constellation)%> |
<%=link_to "users", users_path%> |

<h1>Edit Constellation</h1>

app/views/constellations/index.html.erb
<%=link_to "Dashboard", root_path%> |
<%=link_to "Add a new Constellation", new_constellation_path(@constellation)%> |
<%=link_to "users", users_path%>
<h1>Constellation Lists</h1>
   <%@constellations.each do |cons|%>
   <p><%=link_to cons.constellation_name, constellation_path(cons)%></p>
 <%end%>

app/views/constellations/new.html.erb
<%=render partial: 'cons', locals: {constellation: @constellation} %>

     <%if @constellation.errors.any?%>
        <h3>
            <p><%=pluralize(@constellation.errors.count, "error")%></p>
        </h3>
    <ul>
            <%@constellation.errors.full_messages.each do |m|%>
            <p><li><%=m%></li></p>
      <%end%>
    </ul>
<%end%>

<%=link_to "Dashboard", root_path%> |
<%=link_to "users", users_path%> |
 <%=link_to "Back to Constellations", constellations_path(@constellation)%> 


<h1>New Constellation</h1>
 

<br>


<style>
.field_with_errors {
  color: red;
}
</style>
 

app/views/constellations/show.html.erb
<%=link_to "Home", root_path%> |
 <%=link_to "Back to Constellations", constellations_path(@constellation)%> |
<%=link_to "Add a Constellation", new_constellation_path(@constellation)%> |

<%=link_to "users", users_path%>

    <p><strong>Constellation Name:</strong><%=@constellation.constellation_name%></p>
    <p><strong>Star Name:</strong><%=@constellation.star_name%></p>
    <p><img src="<%=@constellation.image_url%>"/></p>
    <p><strong>Description:</strong><%= @constellation.description%></p>
    
   <%if current_user%>
    <%=link_to "Edit", edit_constellation_path(@constellation)%> | <%=link_to "Delete", constellation_path(@constellation), method: :delete%> |  <%=link_to "Add a Stargazing", new_constellation_stargazing_path(@constellation)%>
<% else %>
<%end%>


<style>
    img {
    height: 400px;
    width: 200 px
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Astrophotography</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!--<%=link_to 'Log Out', logout_path, method: :delete%>-->

<% if !flash[:error].blank? %>
    <div class="error">
      <%= flash[:error] %>
      </div>
  <% end %> 

<% if !flash[:message].blank? %>
  <div class="message">
  <%= flash[:message] %>
  </div>
 <% end %>

 
<%=render_navigation%>

<%= yield %>


  </body>
</html>

app/views/stargazings/index.html.erb
<%=link_to "Dashboard", root_path%> |
<%=link_to "Add a Stargazing", new_stargazing_path(@stargazing)%> |
<%=link_to "users", users_path%> 

<h1>Stargazing Lists</h1>
   <%@stargazings.each do |star|%>
   <p><%=link_to star.constellation.constellation_name, stargazing_path(star)%></p>
 <%end%>   

app/views/stargazings/new.html.erb
<%=link_to "Dashboard", root_path%> |
<%=link_to "users", users_path%> |
<%=link_to "Back to stargazings", stargazings_path(@stargazing)%>


<h1>New stargazing</h1>
  <%=form_for @stargazing do |f|%>
        <%=f.label :constellation_id, 'Constellations:'%>
        <%=f.collection_select :constellation_id, @constellations, :id, :constellation_name%>
        <%=f.label :location%>
        <%=f.text_field :location%>
        <br><br>
        <%=f.label :weather%>
        <%=f.number_field :weather%>
         <br><br>
        <%=f.label :time%>
        <%=f.time_field :time%>
        <br><br>
        <br><br>
        <%=f.submit%>
<%end%>

<style>
.field_with_errors {
  color: red;
}
</style>

app/views/stargazings/show.html.erb
<h1><%=@constellation.constellation_name%></h1>

<h2><%=pluralize(@constellation.stargazings.count, "Constellation")%></h2>
<ul>
    <%@constellation.stargazings.each do |star|%>
    <li><%= link_to star.constellation_name, stargazing_path(star)%></li>
    <%end%>
</ul>

app/views/users/edit.hmtl.erb
<%=form_for @user do |f|%>
        <%=f.label :profile_image%>
        <%=f.text_field :profile_image%>
        <br><br>
        <%=f.label :bio%>
        <%=f.text_field :bio%>
        <br><br>
        <%=f.submit "Update profile"%> 
    <%end%>
        <%=button_to "Delete", user_path(@user), :method => :delete, data:{confirm: "Are you sure you want to delete your account?"}%>
 



  

app/views/users/edit.html.erb
<%=form_for @user do |f|%>
    <%=f.label :profile_image%>
    <%=f.text_field :profile_image%>
    <br><br>
    <%=f.label :bio%>
    <%=f.text_field :bio%>
    <br><br>
    <%=f.submit "Update profile"%> 
<%end%>
    <br><br>
 



  

app/views/users/index.html.erb
<%=link_to "Dashboard", root_path%>
<%=link_to "Constellations", constellations_path(@constellation)%>
<%=link_to "Stargazings", stargazings_path(@stargazing)%> 


<h1>All Astrophotographers</h1>
    <%@users.each do |user|%>
    <p><%= link_to user.username, user_path(user)%></p>
<%end%>

app/views/users/new.html.erb
<div class="message">
<%=flash[:message] if flash[:message]%>
</div>

<h1>Welcome to the World of Astrophotographers!</h1>
<h2>Start here!</h2>
<%=form_for :user do |f|%>
    <%=f.label :username%>
    <%=f.text_field :username%>
    <br><br>
    <%=f.label :password%>
    <%=f.password_field :password%>
    <br><br>
    <%=f.submit "Sign Up"%>
<%end%>

<style>
.message {
    color: green;
}
</style>
<!--

<h1>Welcome to the World of Astrophotographers!</h1>
<h2>Start here!</h2>
<%=form_tag(signup_path) do |f|%>
    <%=text_field_tag :username, nil, :placeholder => "Sign Up" %>
    <%= password_field_tag :password, nil, :placeholder => 'Password' %>
    <%= password_field_tag :profile_image, nil, :placeholder => 'profile_image' %>
    <%= password_field_tag :bio, nil, :placeholder => 'bio' %>
    <%=submit_tag "sign up", class: "sessions"%>
<%end%>
-->
<style>
.message {
    color: green;
}
</style>

app/views/users/show.html.erb
<%=link_to "Dashboard", root_path%>
<%=link_to "back to Astrotographers", users_path%>
<h2><%=@user.username.capitalize%></h2>
<img src="<%=@user.profile_image%>"/>
<h2>Bio <%=@user.bio%></h2>
<%=link_to "Edit profile", edit_user_path(@user)%>
<br><br>
<%if !!!current_user%>
    <%=button_to "Delete", user_path(@user), :method => :delete, data:{confirm: "Are you sure you want to delete your account?"}%>
<%end%>
<style>

img {
height: 150px;
 width: 100 px
}
</style>